# Generated by Django 4.0.4 on 2022-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=50)),
                ('Proyecto', models.CharField(max_length=50)),
                ('IP', models.CharField(max_length=20)),
                ('ID_Labview', models.CharField(max_length=50)),
            ],
        ),
    ]
