# Generated by Django 4.0.4 on 2022-05-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_dispositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='Cantidad_Registros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='Puerto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='Registros',
            field=models.IntegerField(default=0),
        ),
    ]
