# Generated by Django 4.0.4 on 2022-05-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Dispositivos',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='Dispositivo_Principal',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='Marca_Sensor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='Modelo_Sensor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
