# Generated by Django 4.0.4 on 2022-05-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_choice_question_delete_dispositivos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='Dispositivo_Principal',
            new_name='Dispositivo_Comunicación',
        ),
    ]
