# Generated by Django 4.0.4 on 2022-05-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_dispositivo_principal_dispositivo_dispositivo_comunicación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='Dispositivo_Comunicación',
            new_name='Dispositivo_de_Comunicación',
        ),
    ]
