# Generated by Django 4.0.4 on 2022-05-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_dispositivo_comunicación_dispositivo_dispositivo_de_comunicación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='Cantidad_Registros',
            new_name='Cantidad_de_Registros',
        ),
    ]
