# Generated by Django 4.0.4 on 2022-05-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_cantidad_registros_dispositivo_cantidad_de_registros'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='Medición',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
