# Generated by Django 4.0.4 on 2022-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_dispositivo_medición'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='Modbus_ID',
            field=models.IntegerField(default=0),
        ),
    ]
