# Generated by Django 4.0.4 on 2022-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_dispositivo_modbus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='Cantidad_de_Registros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Puerto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='Registros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
